:inoremap { {<CR>}<ESC>O
:inoremap ( ()<ESC>i
:inoremap [ []<ESC>i
:inoremap ' ''<ESC>i
:inoremap " ""<ESC>i
:inoremap ` ``<ESC>i
nnoremap <Tab> <c-w>w
nnoremap <bs> <c-w>W

set number

set autoindent

set cindent

set backspace=2

set tabstop=4
set softtabstop=4

set expandtab
set softtabstop=4

set shiftwidth=4

set ruler

set showmode

nnoremap <F2> :set nonumber!<CR>
set pastetoggle=<F3>

set nowrap

set guifont=YaHei\ Consolas\ 17 " Hybrid\ 17

set background=dark

set hlsearch

syntax on

set cursorline

set t_Co=256

set ic

set enc=utf8

set nocompatible

set ruler

set gcr=a:block-blinkon0

set history=50

let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
:nmap <silent> <Leader>b <Plug>IndentGuidesToggle

set foldmethod=syntax
set nofoldenable
