alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias c='clear'
alias cd..='cd ..'
alias clr='clear'
alias ..='cd ..'
alias lsa='ls -a'
alias rm='rm -i'
alias v='vim'
alias add='git add -A'
alias commit='git commit -m'
alias push='git push'
alias pull='git pull'
alias checkout='git checkout'
alias status='git status'
alias p='python3'

#self define function for git add commit push
acp(){
    add;
    commit "$1";
    push;
}

#Trashing
del() {
    for item in "$@" ;
      do echo "Trashing: $item" ;
      mv "$item" ~/.Trash/;
    done;
}

#Top
function topgrep() {
    if [[ $# -ne 1 ]]; then
        echo "Usage: topgrep <expression>"
    else
        top -pid `pgrep $1`
    fi
}
