alias c='clear'
alias cd..='cd ..'
alias clr='clear'
alias ..='cd ..'
alias lsa='ls -a'
alias ll='ls -l'
alias rm='rm -i'
alias v='vim'
alias add='git add -A'
alias commit='git commit -m'
alias push='git push'
alias pull='git pull'
alias checkout='git checkout'
alias status='git status'
alias p='python3'
alias djan='p manage.py runserver'

#self define function for git add commit push
acp(){
    add;
    commit "$1";
    push;
}
